import pandas as pd
import matplotlib.pyplot as plt
import os
import sys

def plot_results():
    """
    Reads the CSV generated by main.py and plots bar charts for analysis.
    """
    # Path to the results directory and CSV file
    results_dir = "HW2_Results"
    csv_path = os.path.join(results_dir, "metrics_table.csv")

    # Check if the CSV file exists
    if not os.path.exists(csv_path):
        print(f"Error: '{csv_path}' not found. Please run 'main.py' first.")
        return

    # Read the data using pandas
    df = pd.read_csv(csv_path)

    # To keep the charts clean, we only plot results for Intensity = 0.1.
    # You can change this value to 0.05 or 0.2 to see other results.
    target_intensity = 0.1
    df_filtered = df[df['Intensity'] == target_intensity]

    if df_filtered.empty:
        print(f"No data found for intensity {target_intensity}")
        return

    # Get the list of unique noise types present in the data
    noise_types = df_filtered['Noise Type'].unique()

    print(f"Generating charts for Intensity = {target_intensity}...")

    for noise in noise_types:
        # Filter data for the specific noise type (e.g., just 'salt_pepper')
        subset = df_filtered[df_filtered['Noise Type'] == noise]

        # Chart configuration data
        filters = subset['Filter Type']
        corrected = subset['Corrected Pixels (Task4)']
        corrupted = subset['Corrupted Pixels (Task5)']

        x = range(len(filters))
        width = 0.35  # Width of the bars

        fig, ax = plt.subplots(figsize=(10, 6))
        
        # Plot two bars side-by-side:
        # 1. Corrected Pixels (Green) -> The higher, the better
        # 2. Corrupted Pixels (Red)   -> The lower, the better
        bar1 = ax.bar([i - width/2 for i in x], corrected, width, label='Corrected (Good)', color='green')
        bar2 = ax.bar([i + width/2 for i in x], corrupted, width, label='Corrupted (Bad)', color='red')

        # Set labels and titles
        ax.set_xlabel('Filter Type', fontsize=12)
        ax.set_ylabel('Number of Pixels', fontsize=12)
        ax.set_title(f'Performance Analysis for: {noise} Noise (Intensity {target_intensity})', fontsize=14)
        ax.set_xticks(x)
        ax.set_xticklabels(filters, rotation=15)
        ax.legend()

        # Add exact value labels on top of each bar for better readability
        ax.bar_label(bar1, padding=3)
        ax.bar_label(bar2, padding=3)

        plt.tight_layout()

        # Save the chart as a PNG file in the results folder
        save_name = os.path.join(results_dir, f"Chart_{noise}.png")
        plt.savefig(save_name)
        print(f"Saved chart: {save_name}")
        
        # Close the figure to free up memory
        plt.close()

    print("\n✅ All charts generated successfully in 'HW2_Results' folder.")

if __name__ == "__main__":
    plot_results()